apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp
  namespace: icgroup
  labels:
    app: ic-webapp
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ic-webapp
  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      containers:
        - name: ic-webapp
          image: kbysh01/ic-webapp:1.0
          ports:
            - containerPort: 8080
          env:
            - name: ODOO_URL
              value: "http://192.177.10.140:33077"
            - name: PGADMIN_URL
              value: "http://192.177.10.140:33078"

